version: "3.3"

services:
  metabase:
    # build: ./backend
    image: sachin034/metabase:dremio
    # user: "1000:100"
    # volumes:
    #   - ./plugins:/plugins
    # - ./logs/supervisor/supervisor.log:/var/log/supervisor/supervisord.log:rw
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=randombaba
      - MB_DB_HOST=timescaledb
    # stdin_open: true
    # tty: true
    # command: bash -c "/usr/bin/dumb-init /bin/bash"


    ## For commplete local setup (Postgres, adminer, redis)
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_DB: "metabaseappdb"
      POSTGRES_PASSWORD: "randombaba"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 28080:8080

  dremio:
    image: dremio/dremio-oss
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"
    # volumes:
    #   - ./dremio/lake:/lake